name: "Python bindings tests 40"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  tests-40:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    env:
        BIGML_USERNAME: ${{ secrets.BIGML_USERNAME }}
        BIGML_API_KEY: ${{ secrets.BIGML_API_KEY }}
        BIGML_ORGANIZATION: ${{ secrets.BIGML_ORGANIZATION }}
        BIGML_EXTERNAL_CONN_HOST: ${{ secrets.BIGML_EXTERNAL_CONN_HOST }}
        BIGML_EXTERNAL_CONN_PORT: ${{ secrets.BIGML_EXTERNAL_CONN_PORT }}
        BIGML_EXTERNAL_CONN_DB: ${{ secrets.BIGML_EXTERNAL_CONN_DB }}
        BIGML_EXTERNAL_CONN_USER: ${{ secrets.BIGML_EXTERNAL_CONN_USER }}
        BIGML_EXTERNAL_CONN_PWD: ${{ secrets.BIGML_EXTERNAL_CONN_PWD }}
        BIGML_DELTA: 5

    steps:
    - name: Install packages
      uses: actions/checkout@v2
      with:
        ref: actions
    - run: |
        pip install cython
        pip install pystemmer==2.0.0
        pip install .

    - name: Run tests *23 37 38 40 41 45 33*
      run: |
        export TESTS=$(for t in "40" "41" "45" "38"; do ls bigml/tests/*$t*;done|paste -sd ",")
        echo $TESTS
        python setup.py nosetests --nocapture --tests=$TESTS
